### ISSUE TITLE
Assignments must have something on the right-hand side

### ISSUE THREAD

**Issue by Lexikos** [FuPeiJiang/ahk_parser.js#10]
var =  ; comment - old
    var :=  ; comment - new (incorrect)
    var := ""  ; comment - correct

I thought I saw this working for cases without the same-line comment, but testing now, it doesn't appear so.

`var :=` should also be changed to `var := ""` if it appears on its own line (which I suppose is the simplest to detect), but it's invalid even in v1 when used within a parameter or multi-statement expression, so need not be "fixed" there.

**Comment by FuPeiJiang** [comment]
#9
```
if a=  ; old & new (incorrect)
if a=""  ; correct
```
this part covers it
___
yeah, I won't fix it, I'd have to add that logic around v2Expression
