### ISSUE TITLE
numeric string + 0

### ISSUE THREAD

**Issue by robmunger** [FuPeiJiang/ahk_parser.js#20]
@FuPeiJiang Thanks again for this great script. I converted 1221 lines of a large script, but the converter crashes on the following code.

If I replace "_AllIDsString .= (AllWindows%A_Index%**+0**) "|"_" with "_AllIDsString .= (AllWindows%A_Index%) "|"_"  (ie I remove the "+0") the code converts. 

Thanks!

	PurgeWinList() {
		WinGet, AllWindows, List
		AllIDsString := ""
		Loop, %AllWindows% {
			AllIDsString .= (AllWindows%A_Index%+0) "|"
		}
		Sort, AllIDsString, D|
		For Key, Val in this.Windows {
			If(!InStr(AllIDsString,Key)) { 
				this.DeleteProfile(Key)
			}
		}
	}

**Comment by FuPeiJiang** [comment]
I've isolated it to:
`v:=2 "s"`

woops, I didn't put
`lineWhereCanConcat = i`
after
`everything.push({type:'Integer',text:fEvalidName,i1:i,c1:nonWhiteSpaceStart,c2:c})`

ok, now Integers can concat
~doesn't freeze anymore~
should be fixed

**Comment by robmunger** [comment]
Bravo!
