### ISSUE TITLE
Else if var in String

### ISSUE THREAD

**Issue by robmunger** [FuPeiJiang/ahk_parser.js#21]
I have found another issue which causes my script conversion to freeze. It seems to have something to do with the string, "else if Cmd in ChildCount,Selection,Focus" in the following....

Other than that, it is able to convert my entire 3000 line script. I've been working on this script for 5 years now... that's pretty robust!
   
if (Cmd = "Location")
	AccObj.MyMethod()
   else if Cmd in ChildCount,Selection,Focus
	ret_val := AccObj.MyMethod()

**Comment by FuPeiJiang** [comment]
`if var in a,b,c`
how do you translate this to v2 ?
___
https://lexikos.github.io/v2/docs/Variables.htm#in
> **in** and **contains** are reserved for future use.
___
https://www.autohotkey.com/boards/viewtopic.php?f=37&t=43593
if var in/contains comma-separated list/array
___
I would do it like this:
`if var contains Mon,Tue,Wed,Thu,Fri,Sat,Sun`
would become
`if (Map("mon",1,"tue",1,"wed",1,"thu1","fri",1,"sat",1,"sun",1).Has(StrLower(var))))`
but this loses the point: it loses readability
```autohotkey
var:="Mon"
var:="mon"
var:="nope"
if (Map("mon",1,"tue",1,"wed",1,"thu",1,"fri",1,"sat",1,"sun",1).Has(StrLower(var)))
Msgbox 1
else
Msgbox 2
```
but you should save this Map to a variable for performance reasons, to not recreate the Map every time

StringCaseSense On can be used to make the comparison case sensitive.
https://www.autohotkey.com/docs/commands/IfIn.htm#Remarks
using this information, I can update `Map.CaseSense` accordingly
https://lexikos.github.io/v2/docs/objects/Map.htm#CaseSense

**Comment by FuPeiJiang** [comment]
I updated the website, but you probably need to disable cache just once
![image](https://user-images.githubusercontent.com/42662615/128220874-529dfce2-dcc4-4a54-9c1e-94c8c3f8afc9.png)
1. open chrome devtools, go to Network tab
2. check disable cache
3. reload page
4. uncheck disable cache

**Comment by robmunger** [comment]
Thank you! That is a very elegant substitution.

**Comment by FuPeiJiang** [comment]
credits:
kczx3
guest3456
for that solution
